name: 'Docker Login'
description: 'GitHub Action to login against a Docker registry'
inputs:
  registry:
    description: 'Server address of Docker registry. If not set then will default to Docker Hub'
    required: false
  username:
    description: 'Username used to log against the Docker registry'
    required: true
  password:
    description: 'Password or personal access token used to log against the Docker registry'
    required: true
  logout:
    description: 'Log out from the Docker registry at the end of a job'
    default: 'true'
    required: false
runs:
  using: 'node12'
  main: 'index.js'