version: '3.8'
services:
  rt_msql:
    container_name: rtm1
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=StrongRootPass
      - MYSQL_DATABASE=rtdb
      - MYSQL_USER=rtadm
      - MYSQL_PASSWORD=rtadmusrPass
    ports:
      - 3306:3306
    volumes:
      - dataVolume:/var/lib/mysql
  rt_gin:
    container_name: rtg1
    image: golang:1.17.6-stretch
    command: /bin/bash
    stdin_open: true
    tty: true
    environment:      
      - DATABASE_HOST=rt_msql
      - DATABASE_PORT=3306
      - DATABASE_NAME=rtdb
      - DATABASE_USER=rtadm
      - DATABASE_PASS=rtadmusrPass
    depends_on:
      - rt_msql
    ports:
      - 8080:8080
    volumes:
      - ./gin/:/gin/
volumes:
  dataVolume:

networks:
  default: 
    external: true
    name: rt

