version: '3.8'
services:
  mtu_msql:
    container_name: mtum1
    image: mysql:8.0.28
    environment:
      - MYSQL_ROOT_PASSWORD=StrongRootPass
      - MYSQL_DATABASE=mtudb
      - MYSQL_USER=mtuadm
      - MYSQL_PASSWORD=mtuadmusrPass
    pomtus:
      - 3306:3306
    volumes:
      - dataVolume:/var/lib/mysql
  mtu_gin:
    container_name: mtug1
    image: golang:1.17.6-stretch
    command: /bin/bash
    stdin_open: true
    tty: true
    environment:      
      - DATABASE_HOST=mtu_msql
      - DATABASE_POmtu=3306
      - DATABASE_NAME=mtudb
      - DATABASE_USER=mtuadm
      - DATABASE_PASS=mtuadmusrPass
    depends_on:
      - mtu_msql
    pomtus:
      - 8080:8080
    volumes:
      - ./gin/:/gin/
volumes:
  dataVolume:

networks:
  default: 
    external: true
    name: mtu

