name: build-image-push

on:
  push:
    branches:
      - 'gh_actions'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: docker login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        run: |
          docker build -t sradhugeek/meetup:v${{ env.GITHUB_RUN_NUMBER }} -f Dockerfile .
          docker push sradhugeek/meetup:v${{ env.GITHUB_RUN_NUMBER }}