name: on-push-shell

on:
  push:
    branches:
      - main
      - gh_actions

env:
  CUR_TUES_DATE: 21

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: print values
        if: env.CUR_TUES_DATE > 16 && env.CUR_TUES_DATE < 23
        run: |
          echo ${{ env.CUR_TUES_DATE }}
          export CUR_TUES_DATE=`date +%d`
          echo ${{ env.CUR_TUES_DATE }}
      - name: test values
        run: |
          if [ `date +'%d' | sed 's/^0*//'` -le 22 ]; then
            echo ${{ env.CUR_TUES_DATE }}
            export CUR_TUES_DATE=`date +%d`
            echo ${{ env.CUR_TUES_DATE }}
          else
            echo `date +'%d' | sed 's/^0*//'`
          fi
      