name: on-push-shell

on:
  push:
    branches:
      - main
      - gh_actions

env:
  CUR_TUES_DATE: 21

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: print values
        if: env.CUR_TUES_DATE > 16 && env.CUR_TUES_DATE < 23
        run: |
          echo ${{ env.CUR_TUES_DATE }}
          export CUR_TUES_DATE=`date +'%d' | sed 's/^0*//'`
          echo ${{ env.CUR_TUES_DATE }}
      - name: test values
        if: `date +'%d' | sed 's/^0*//'` -le 22 ] && [ `date +'%d' | sed 's/^0*//'` -ge 15
        run: |
            echo ${{ env.CUR_TUES_DATE }}
            export CUR_TUES_DATE=`date +'%d' | sed 's/^0*//'`
            echo ${{ env.CUR_TUES_DATE }}
            echo `date +'%d' | sed 's/^0*//'`
          
